title: Default Page

tabs:
  content:
    icon: Text
    label: Content
    columns:
      main:
        width: 2/3
        sections:
          fields:
            type: fields
            fields:
              text:
                type: textarea
                size: huge
      sidebar:
        width: 1/3
        sections:
          pages:
            type: pages
            template: default
          files:
            type: files

  meta: tabs/meta/page
